
### 1. Spieler erstellen
POST http://localhost:8080/api/players
Content-Type: application/json

{
  "name": "Dobby"
}

### 1. Spieler erstellen
POST http://localhost:8080/api/players
Content-Type: application/json

{
  "name": "Mattes"
}

### 2. Würfeln (Platzhalter - UUID erst gleich einfügen!)
POST http://localhost:8080/api/players/35dd999d-6983-4da9-8c85-0da19d8d6eb1/roll-virtual

### 2. Würfeln (Platzhalter - UUID erst gleich einfügen!)
POST http://localhost:8080/api/players/45e50874-b41d-4703-a30b-5dd5dd3fa6f8/roll-virtual