spring.application.name=schocken-web-app
server.port=8080

# H2 Konsole aktivieren
spring.h2.console.enabled=true

# Feste URL für die Datenbank vergeben (damit sie sich nicht ständig ändert)
spring.datasource.url=jdbc:h2:mem:schockendb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Sorgt dafür, dass die Datenbank in der Konsole sichtbar bleibt
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update